[package]
name = "yamdr-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
clap = { version = "4.4.1", features = ["derive"] }
futures = "0.3.28"
md = { path = "../md" }
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = "0.1.14"
